### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by arianaa30** [anaskhan96/Crash-Alert#1]
Hi,
Is the crash detection models (if any) created based on a crash accelerometer dataset? If so, is the dataset available somewhere?
I am trying to run your app, but not sure how to test it. Maybe I should be in a real accident?!

**Comment by anaskhan96** [comment]
The alert service is triggered when the phones encounters a back and forth jerk within a small interval of time. [These four values](https://github.com/anaskhan96/Crash-Alert/blob/f02735d6f84541095d369694430d2ffda02a5c8d/app/src/main/java/com/example/anask/myapplication/ShakeListener.java#L10) in the `ShakeListener` class determine that. These values were come upon through trials of giving jerks to the phone. You can test the app the same way.

**Comment by MithilaSutar-09** [comment]
There some gradle issue exicuting plz tell the solution how to run your code
